name: Deploy Nginx to AKS

on:
  push:
    branches:
    - main

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Required to read repository contents
  actions: read # Required for GitHub Actions
  checks: write # Required for status checks

env:
  RESOURCE_GROUP: myResourceGroup2
  AKS_CLUSTER_NAME: myAKSCluster

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Set up Kubernetes tools
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Setup kubelogin
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.26'

    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ env.RESOURCE_GROUP }}'
        cluster-name: '${{ env.AKS_CLUSTER_NAME }}'
        admin: 'false'
        use-kubelogin: 'true'

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v3
      with:
        manifests: |
          k8s/nginx-deployment.yml
          k8s/nginx-service.yml
        images: |
          nginx:latest
        namespace: default
        traffic-split-method: pod
